package com.limonnana.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MiscellaneousAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiscellaneousAllPropertiesEquals(Miscellaneous expected, Miscellaneous actual) {
        assertMiscellaneousAutoGeneratedPropertiesEquals(expected, actual);
        assertMiscellaneousAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiscellaneousAllUpdatablePropertiesEquals(Miscellaneous expected, Miscellaneous actual) {
        assertMiscellaneousUpdatableFieldsEquals(expected, actual);
        assertMiscellaneousUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiscellaneousAutoGeneratedPropertiesEquals(Miscellaneous expected, Miscellaneous actual) {
        assertThat(actual)
            .as("Verify Miscellaneous auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiscellaneousUpdatableFieldsEquals(Miscellaneous expected, Miscellaneous actual) {
        assertThat(actual)
            .as("Verify Miscellaneous relevant properties")
            .satisfies(a -> assertThat(a.getLastUpdate()).as("check lastUpdate").isEqualTo(expected.getLastUpdate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMiscellaneousUpdatableRelationshipsEquals(Miscellaneous expected, Miscellaneous actual) {
        // empty method
    }
}
